server:
  port: 8765
spring:
  application:
    name: api-geteway
zuul:
  routes:
    user:
      path: /user/**
      serviceId: simple-user-service
    movie:
      path: /movie/**
      serviceId: simple-movie-service
  add-host-header: true
  sensitive-headers: 
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
