spring:
  application:
    name: simple-user-service
server:
  port: 8764
eureka:
  client:
    service-url:
      #defaultZone: http://admin:admin@localhost:8761/eureka/
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true